---
window_button_layout: ':minimize,maximize,close'

system_font: 'Roboto 12'
monospace_font: 'JetBrainsMono Nerd Font Medium 14'
document_font: 'Roboto 12'
desktop_font: 'Roboto 12'

gtk_theme: 'ARK-Dark'