---
- name: setup hacking environment
  hosts: localhost
  connection: local

  roles:
  - system
  - tools
  - firefox-burpsuite
  - terminal
  - clipboard-manager  
  - fonts
  - mate-config
  - vscode-config
  - dotfiles