---
- name: configure user sudoers
  include_tasks: user.yml
  tags: system

- name: configure system keyboard layout
  include_tasks: keyboard.yml
  tags: system

- name: configure system timezone
  include_tasks: timezone.yml
  tags: system

- name: install system scripts
  include_tasks: scripts.yml
  tags: system