---
- name: remove unofficial docker packages
  apt:
    name: 
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
    state: absent
  register: docker_remove
  become: true
  tags: docker

- name: remove containerd/runc if docker was removed
  apt:
    name: 
      - containerd
      - runc
    state: absent
  when: docker_remove.changed
  become: true
  tags: docker

- name: install docker prerequisites
  apt:
    name:
      - ca-certificates
      - curl
    state: latest
  become: true
  tags: docker

- name: create apt keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  tags: docker

- name: download docker GPG key
  get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  tags: docker

- name: install docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ docker_distribution }} stable"
    state: present
    update_cache: true
  become: true
  tags: docker

- name: upgrade all packages
  apt: 
    upgrade: true 
    force_apt_get: true
  become: true
  tags: docker

- name: install docker packages
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  become: true
  tags: docker

- name: disable docker from starting on boot to preserve resources
  systemd:
    name: docker
    enabled: false
    state: stopped
  become: true
  tags: docker

- name: disable containerd from starting on boot
  systemd:
    name: containerd
    enabled: false
    state: stopped
  become: true
  tags: docker

- name: add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  become: true
  tags: docker
