---
# MATE Desktop Configuration Variables
# Window manager settings (buttons on the right)
window_button_layout: 'menu:minimize,maximize,close'

# Font settings
system_font: 'Roboto 12'
monospace_font: 'JetBrainsMono Nerd Font Medium 14'
document_font: 'Roboto 12'
desktop_font: 'Roboto 12'

# Theme settings
gtk_theme: 'ARK-Dark'
